source 'https://rubygems.org'

gem 'puma'
gem 'fog'
gem "omniauth-google-oauth2"
gem 'jquery-fileupload-rails'
gem 'omniauth-facebook'
gem 'twitter'
gem 'omniauth-twitter'
gem 'kaminari-bootstrap'
gem 'kaminari', '~> 0.16.1'
gem 'pry'
gem 'cocoon'
gem 'bcrypt', '~> 3.1.7'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'font-awesome-sass', '~> 4.5.0'
gem 'jquery-ui-rails'
gem 'jquery-turbolinks'
gem 'cancancan'
gem 'quiet_assets'
gem 'delayed_job_active_record'
gem 'delayed_job_web'
gem 'chosen-rails'
gem 'rails_12factor', group: :production
gem 'simple_form'
gem 'friendly_id'
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
gem 'mini_magick'
gem 'rails', '4.2.6'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'faker', github: 'stympy/faker'
  gem 'cowsay'
  gem 'rails-erd'
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'letter_opener'
  gem 'interactive_editor'
  gem 'spring'
  gem 'awesome_print'
  gem 'hirb'
end
